FROM	alpine

MAINTAINER focudert <fcoudert@student.42.fr>

RUN	apk update && apk add nginx ; \
	apk add --no-cache openrc openssl openssh

RUN	mkdir -p var/run/nginx

COPY	index_nginx.html /www/

RUN	rm /etc/nginx/nginx.conf
COPY	nginx.conf /etc/nginx/nginx.conf

RUN	openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/example.key -out /etc/nginx/example.crt -subj "/C=FR/ST=IDE/L=Paris/O=42/OU=42/CN=mywebsite.com" 

EXPOSE	80 443

CMD	nginx -g "daemon off;"