FROM	alpine

MAINTAINER focudert <fcoudert@student.42.fr>

RUN	apk update && apk add nginx && apk add wget ; \
    apk add --no-cache php7 php7-fpm php7-opcache php7-common ; \
    apk add php7-gd php7-mysqli php7-zlib php7-curl ; \
	apk add php-json supervisor; \
	apk add --update cache ; \
	apk add php-bz2 ; \
	apk add --no-cache openrc openssl openssh

#RUN wget http://wordpress.org/latest.tar.gz \
#		&& tar xzvf latest.tar.gz \
#		&& mv wordpress var/www/wordpress \
#		&& rm latest.tar.gz
 		
#RUN chmod -R 755 /var/www/wordpress

RUN apk add curl ; \
		apk add php-phar ; \
		apk add sudo ; \
		apk add php7-iconv ; \
		curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar ; \
		chmod +x wp-cli.phar ; \
		sudo mv wp-cli.phar /usr/local/bin/wp ; \
		apk add mysql-client

RUN	mkdir -p var/run/nginx

COPY	index_nginx.html var/www/

RUN	rm /etc/nginx/nginx.conf
COPY	my_nginx.conf /etc/nginx/nginx.conf

COPY entry.sh .

RUN chmod 777 entry.sh




#RUN	openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/nginx/example.key -out /etc/nginx/example.crt -subj "/C=FR/ST=IDE/L=Paris/O=42/OU=42/CN=mywebsite.com" 

COPY /wp-config.php /www/wordpress/

COPY    start.sh .
RUN	chmod +x start.sh

EXPOSE 5050

#EXPOSE	80 443

CMD	["sh", "./start.sh" ]