apiVersion: v1
kind: Service
metadata:
  annotations:
    metallb.universe.tf/allow-shared-ip: "true"
  name: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
  - port: 5050
    targetPort: 5050
    name: wordpress

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: alpine_wordpress
        imagePullPolicy: Never
        ports:
        - containerPort: 5050

#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: wp-pv-claim
#  labels:
#    app: wordpress
#spec:
#  accessModes:
#    - ReadWriteOnce
#  resources:
#    requests:
#      storage: 1Gi
#---

# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: wp-pv-claim
#   labels:
#     app: wordpres
# spec:
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 1Gi

#         volumeMounts:
#         env:
#         - name: WORDPRESS_DB_HOST
#           value: user
#         - name: WORDPRESS_DB_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mysql-pass
#               key: password
#         ports:

#         - name: wordpress-persistent-storage
#           mountPath: /var/www/html
#       volumes:
#       - name: wordpress-persistent-storage
#         persistentVolumeClaim:
#           claimName: wp-pv-claim