apiVersion: v1
kind: Service
metadata:
  name: telegraf
spec:
  type: ClusterIP
  selector:
    app: telegraf
  ports:
  - port: 8185
    targetPort: 8185
    name: telegraf

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegraf-deployment
  labels:
    app: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      containers:
      - name: telegraf
        image: alpine_telegraf
        imagePullPolicy: Never
        ports:
          - containerPort: 8185